title: pwn2own1337
description: pwn2own
template:
  repo: pwn2own1337-template
  name: pwn2own1337
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
